-- MySQL Script generated by MySQL Workbench
-- Thu Feb 18 13:50:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nivell1-pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nivell1-pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nivell1-pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `nivell1-pizzeria` ;

-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`provinces` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`towns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`towns` (
  `town_id` INT NOT NULL AUTO_INCREMENT,
  `town_namel` VARCHAR(45) NOT NULL,
  `provinces_province_id` INT NOT NULL,
  PRIMARY KEY (`town_id`, `provinces_province_id`),
  INDEX `fk_towns_provinces1_idx` (`provinces_province_id` ASC) VISIBLE,
  CONSTRAINT `fk_towns_provinces1`
    FOREIGN KEY (`provinces_province_id`)
    REFERENCES `nivell1-pizzeria`.`provinces` (`province_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NOT NULL,
  `client_surname` VARCHAR(45) NOT NULL,
  `client_adress` VARCHAR(45) NOT NULL,
  `client_postcode` VARCHAR(45) NOT NULL,
  `client_telephone` INT NOT NULL,
  `towns_town_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `towns_town_id`),
  INDEX `fk_clients_towns1_idx` (`towns_town_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_towns1`
    FOREIGN KEY (`towns_town_id`)
    REFERENCES `nivell1-pizzeria`.`towns` (`town_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`shops` (
  `shop_id` INT ZEROFILL NOT NULL,
  `shop_adress` VARCHAR(45) NOT NULL,
  `shop_postcode` VARCHAR(45) NOT NULL,
  `towns_town_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `towns_town_id`),
  INDEX `fk_shops_towns1_idx` (`towns_town_id` ASC) VISIBLE,
  CONSTRAINT `fk_shops_towns1`
    FOREIGN KEY (`towns_town_id`)
    REFERENCES `nivell1-pizzeria`.`towns` (`town_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`workers` (
  `worker_id` INT NOT NULL,
  `worker_name` VARCHAR(45) NOT NULL,
  `worker_surname` VARCHAR(45) NOT NULL,
  `workers_nif` VARCHAR(15) NOT NULL,
  `worker_telephone` INT NOT NULL,
  `worker_role` VARCHAR(45) NOT NULL COMMENT 'if the worker is a cooker or a deliverer. ',
  `shops_shop_id` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`worker_id`, `shops_shop_id`),
  INDEX `fk_workers_shops1_idx` (`shops_shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_shops1`
    FOREIGN KEY (`shops_shop_id`)
    REFERENCES `nivell1-pizzeria`.`shops` (`shop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order_shipment` VARCHAR(3) NOT NULL COMMENT 'yes -  if shipment is needed\nno - if there is no shipment',
  `order_totalPrice` INT NOT NULL,
  `order_pizzaCount` INT NULL,
  `order_hamburguerCount` INT NULL,
  `order_drinkCount` INT NULL,
  `order_deliverTime` DATE NULL,
  `workers_worker_id` INT NULL,
  `shops_shop_id` INT ZEROFILL NOT NULL,
  `clients_client_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `shops_shop_id`, `clients_client_id`),
  INDEX `fk_orders_shops1_idx` (`shops_shop_id` ASC) VISIBLE,
  INDEX `fk_orders_workers1_idx` (`workers_worker_id` ASC) VISIBLE,
  INDEX `fk_orders_clients1_idx` (`clients_client_id` ASC) VISIBLE,
  UNIQUE INDEX `workers_worker_id_UNIQUE` (`workers_worker_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_shops1`
    FOREIGN KEY (`shops_shop_id`)
    REFERENCES `nivell1-pizzeria`.`shops` (`shop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_workers1`
    FOREIGN KEY (`workers_worker_id`)
    REFERENCES `nivell1-pizzeria`.`workers` (`worker_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`clients_client_id`)
    REFERENCES `nivell1-pizzeria`.`clients` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` VARCHAR(45) NOT NULL,
  `product_image` VARCHAR(45) NOT NULL,
  `product_price` INT NOT NULL,
  `category_category_id` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_category1_idx` (`category_category_id` ASC) VISIBLE,
  UNIQUE INDEX `category_category_id_UNIQUE` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `nivell1-pizzeria`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivell1-pizzeria`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nivell1-pizzeria`.`orders_has_products` (
  `orders_order_id` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`orders_order_id`, `products_product_id`),
  INDEX `fk_orders_has_products_products1_idx` (`products_product_id` ASC) VISIBLE,
  INDEX `fk_orders_has_products_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `nivell1-pizzeria`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `nivell1-pizzeria`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
